### ISSUE TITLE
Suggestion - Using msgpack to reduce connection costs

### ISSUE THREAD

**Issue by Potato1682** [psac-serve/ban-server#2]
通信のショートカットコードなどを使うmsgpackを使用して通信を行うと、通信の際さらに処理速度が向上できると思います。
msgpackはさまざまな言語にAPIを提供しており、実際にコードエディタの一つであるneovimが使用し確かな処理速度の向上がわかっています。

**Comment by peyang-Celeron** [comment]
つよそうなのでMsgPack使おうと思います(即決

**Comment by peyang-Celeron** [comment]
0fe418258c3f82742ca4a5eb533e5913451f96af により解決されました。

**Comment by peyang-Celeron** [comment]
[Release 2.0](https://github.com/psac-serve/ban-server/releases/tag/2.0) が公開されました。
